### ISSUE TITLE
Please add example for write_multiple_registers

### ISSUE THREAD

**Issue by kang2k10** [alextingle/Modbus-Master-Slave-for-Arduino#1]
Please add example for write_multiple_registers
i add in code telegram.fc_write_multiple_registers(1, 40000, 2);
but master send to slave - zerro

**Comment by alextingle** [comment]
The test harness contains examples for all functions. Look in test/echo/echo.ino.

In this case, you also need to set the *values* that you want to send.

    uint16_t data[] = { 1111, 2222 };
    telegram.fc_write_multiple_registers(1, 40000, 2);
    telegram.set_registers(data, 2); // <=========== call this function
    master.send_request(telegram);

**Comment by kang2k10** [comment]
Verry  thanks. All work!

**Comment by alextingle** [comment]
Fantastic. Good luck.
