### ISSUE TITLE
need help for dynamic ID

### ISSUE THREAD

**Issue by c0zm0z** [alextingle/Modbus-Master-Slave-for-Arduino#2]
Hello Alextingle, 
thank you very much for that improved lib.

I was trying to get a programmable configuration of the modbus settings ID; Boudrate; SerialSetting (for Example.8N1 or 8E1).
Boudrate is easy until 65.000
Serialsettings can be 0x00-0x20 or whatever is possible.

My problem is how can i change the ID if the controller is running without reprogramming.

I write the values in an EEPROM and read it at start, but the Slave slave(ID,Serial1,0) instance was created befor the setup() started. 

I set some default values by pressing a button :-).

Can you send me a hint, how i can change the ID at runtime?
I know i should restart the controller after any change.

SOLVED sorry, didn't found slave.setID function

**Comment by alextingle** [comment]
Glad you found the solution!
